version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    environment:
      SERVER_NAME: elasticsearch
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    ports:
      - 5601:5601
    ulimits:
      nproc: 65536
      memlock:
        soft: -1
        hard: -1
    networks:
      - back
networks:
  ## BEGIN networks ##
  back:
    driver: bridge
  ## END networks ##