services:
    fantasy_demo.layout.data_provider.product:
        class: 'Fantasy\Bundle\DemoBundle\Layout\DataProvider\ProductProvider'
        tags:
            - { name: layout.data_provider, alias: product_stock }

    fantasy_demo.layout.data_provider.order:
        class: 'Fantasy\Bundle\DemoBundle\Layout\DataProvider\OrderProvider'
        tags:
            - { name: layout.data_provider, alias: order_data }


    fantasy_demo.event_listener.order_history_listener:
        class: Fantasy\Bundle\DemoBundle\EventListener\OrderHistoryListener
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.base-orders-grid, method: onBuildBefore }
