parameters:
    on_delivery.method.identifier_prefix.on_delivery: 'on_delivery'

services:
    fantasy_demo.layout.data_provider.product:
        class: 'Fantasy\Bundle\DemoBundle\Layout\DataProvider\ProductProvider'
        tags:
            - { name: layout.data_provider, alias: product_stock }

    fantasy_demo.layout.data_provider.order:
        class: 'Fantasy\Bundle\DemoBundle\Layout\DataProvider\OrderProvider'
        tags:
            - { name: layout.data_provider, alias: order_data }


    fantasy_demo.event_listener.order_history_listener:
        class: Fantasy\Bundle\DemoBundle\EventListener\OrderHistoryListener
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.frontend-orders-grid, method: onBuildBefore }

    fantasy_on_delivery.generator.on_delivery_config_identifier:
        parent: oro_integration.generator.prefixed_identifier_generator
        public: true
        arguments:
            - '%on_delivery.method.identifier_prefix.on_delivery%'

    fantasy_on_delivery.integration.channel:
        class: Fantasy\Bundle\DemoBundle\Integration\OnDeliveryChannelType
        public: true
        tags:
            - { name: oro_integration.channel, type: on_delivery }

    fantasy_on_delivery.integration.transport:
        class: Fantasy\Bundle\DemoBundle\Integration\OnDeliveryTransport
        public: false
        tags:
            - { name: oro_integration.transport, type: on_delivery, channel_type: on_delivery }

    fantasy_on_delivery.factory.on_delivery_config:
        class: Fantasy\Bundle\DemoBundle\PaymentMethod\Config\Factory\OnDeliveryConfigFactory
        public: false
        arguments:
            - '@oro_locale.helper.localization'
            - '@fantasy_on_delivery.generator.on_delivery_config_identifier'

    fantasy_on_delivery.payment_method.config.provider:
        class: Fantasy\Bundle\DemoBundle\PaymentMethod\Config\Provider\OnDeliveryConfigProvider
        arguments:
            - '@doctrine'
            - '@logger'
            - '@fantasy_on_delivery.factory.on_delivery_config'

##################################### OnDelivery Integration ##################################
# This wasnt in the documentation but I assume is the service needed to inject in the provider
    fantasy_on_delivery.factory.method_view.on_delivery:
        class: Fantasy\Bundle\DemoBundle\PaymentMethod\View\Factory\OnDeliveryViewFactory
        public: false
#****************************************************************************************
    fantasy_on_delivery.payment_method_view_provider.on_delivery:
        class: Fantasy\Bundle\DemoBundle\PaymentMethod\View\Provider\OnDeliveryViewProvider
        public: false
        arguments:
            - '@fantasy_on_delivery.payment_method.config.provider'
            - '@fantasy_on_delivery.factory.method_view.on_delivery'
        tags:
            - { name: oro_payment.payment_method_view_provider }

    fantasy_on_delivery.factory.method.on_delivery:
        class: Fantasy\Bundle\DemoBundle\PaymentMethod\Factory\OnDeliveryPaymentMethodFactory
        public: false

    fantasy_on_delivery.payment_method_provider.on_delivery:
        class: Fantasy\Bundle\DemoBundle\PaymentMethod\Provider\OnDeliveryMethodProvider
        public: false
        arguments:
            - '@fantasy_on_delivery.payment_method.config.provider'
            - '@fantasy_on_delivery.factory.method.on_delivery'
        tags:
            - { name: oro_payment.payment_method_provider }

    fantasy_on_delivery.event_listener.on_delivery_order_listener:
        class: Fantasy\Bundle\DemoBundle\EventListener\OnDeliveryOrderListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
            - '@oro_entity.doctrine_helper'
            - '@fantasy_on_delivery.payment_method.config.provider'
##################################### End of OnDelivery Integration ##################################
